### ISSUE TITLE
Error when running cdk synth

### ISSUE THREAD

**Issue by shepherdjerred** [ScottBrenner/aws-cdk-action#23]
Thanks for creating this repository -- I've found it very helpful!

I have the following job:
```
  synth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: CDK Synth
        uses: scottbrenner/aws-cdk-action@master
        with:
          args: synth
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: cdk.out
```
[Link to job YAML](https://github.com/shepherdjerred/aws-docker-cdk/blob/main/.github/workflows/cicd.yml)

This error occurs:
```
Run scottbrenner/aws-cdk-action@master
/usr/bin/docker run --name a33c151d53b57ecef410d839188e68ad94f40_a898d9 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/aws-docker-cdk/aws-docker-cdk":"/github/workspace" 8a33c1:51d53b57ecef410d839188e68ad94f40 synth
Error: EACCES: permission denied, open 'cdk.out/tree.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at TreeMetadata._synthesizeTree (/github/workspace/node_modules/monocdk/lib/core/lib/private/tree-metadata.ts:56:12)
    at /github/workspace/node_modules/monocdk/lib/core/lib/private/synthesis.ts:168:23
    at visit (/github/workspace/node_modules/monocdk/lib/core/lib/private/synthesis.ts:209:9)
    at visit (/github/workspace/node_modules/monocdk/lib/core/lib/private/synthesis.ts:206:9)
    at synthesizeTree (/github/workspace/node_modules/monocdk/lib/core/lib/private/synthesis.ts:158:5)
    at Object.synthesize (/github/workspace/node_modules/monocdk/lib/core/lib/private/synthesis.ts:31:5)
    at App.synth (/github/workspace/node_modules/monocdk/lib/core/lib/stage.ts:74:29)
    at process.<anonymous> (/github/workspace/node_modules/monocdk/lib/core/lib/app.ts:50:51)
Subprocess exited with error 1
```
[Link to example run](https://github.com/shepherdjerred/aws-docker-cdk/runs/3138263870?check_suite_focus=true)

It seems like there is no permission to write to cdk.out.
